### ISSUE TITLE
Review and questions

### ISSUE THREAD

**Issue by amercader** [datopian/ckanext-asset-storage#8]
@shevron overall the extension is excellent as usual, no issues code-wise, uses all the right interfaces and is well documented and tested.

Two general questions:

* Why have the assets (eg group/org/user pics) managed in a separate extension than the resources (ckanext-blob-storage)? I get that there are internal differences like the Uploader classes or the resources having maybe a different processing and using Git LFS but conceptually they are just uploads (or just blob storage), and from the user point of view it seems weird having to install and configure two different extensions (And to be fair, it felt like having to install yet another piece of an already big puzzle). I'm sure there are good reasons but just want to understand the overall thinking.

* Is there a reason the download URLs on this extension don't follow the existing CKAN pattern (eg `/uploads/group/{date}-{filename}` -> `/assets/group/{date}-{filename}`? If they did it would make transitioning from local storage or from ckanext-cloudstorage much easier, as URLs get stored in the DB for each org/group/etc

**Comment by shevron** [comment]
@amercader both good points.

* re a separate extension: the mechanics of blob-storage and Git LFS are pretty complex, and using the same code / infrastructure to store assets makes no sense and is total overkill, and would have required tons of extra work (the flow of downloading from Git LFS is *way* more complex than what would be supported by an `<img src="...">` tag for example). We could have combined the two in the same extension (actually the objection you bring up was brought up by others as well) even through the code would be entirely separate, just to simplify deployment. But I think that:
  * This would have introduced some confusion, as even the configuration is not similar between the two. asset-storage lets you configure the cloud storage settings directly in the CKAN INI, while blob-storage only lets you configure the URL of the LFS serer, and the LFS server has all the cloud storage configuration in it. I think that would be a potential point of confusion, as if it was a single extension I would have expected to also share storage configuration. 
  * Just from a design philosophy standpoint (and I admit that here I may be a bit of a purist and may have a tendency to choose less pragmatically...) I just like the UNIX philosophy of having small tools that do one thing. Since I think the requirements of asset uploading and management are very different from the requirements for resource uploading and management, I just preferred to keep them separate. 

* re URL - that is a great point. I actually think that it is oversight on my part and should be fixed. I remember seeing the `/uploads/` URL and for some reason making the decision to not use it, but I don't remember even why... I think it makes sense to use `/uploads`/.

**Comment by amercader** [comment]
Thanks for the detailed answer @shevron.

If we set aside the versioning and revisioning features, are the requirements of resource uploading that different from the assets ones? I totally see how these extra requirements make necessary things like Git LFS and the rest, but I'm not sure the added complexity would justify the new features to the average CKAN maintainer. I'd imagine most users just want to store resource blobs in the cloud (in pretty much the same way assets are handled in this extension)

I guess that what I'm saying is that now we have these extensions:

1. cloud storage for assets
2. cloud storage for resources with versioning (requires giftless, etc)

Would it make sense to have simpler version for resources:

1. cloud storage for assets
2. cloud storage for resources
3. cloud storage for resources with versioning (requires giftless, etc)

At which point that can probably be simplified:

1. cloud storage for assets and resources
2. cloud storage for resources with versioning (requires giftless, etc)

I'm not criticizing the choices made as like you said they make sense in the context of the project this was developed under, I'm just thinking in terms of wider adoption.

On another note, I'm not a massive fan of `assets` as way to describe non-resource blobs. We (and most of the web community) tend to use assets for files used by the frontend like js and css (see eg [these docs](https://docs.ckan.org/en/2.9/theming/webassets.html)), which are not related to this extension at all. I guess the more precise term would be `uploads` but if you want to differentiate them from resources I don't have a better alternative.

**Comment by shevron** [comment]
Yes, I think what you are saying makes sense. @rufuspollock and I had a similar discussion when we kicked this off (and also discussed naming which obviously should be different for an extension doing both assets / static files and resources). 

The LFS route makes sense only in the context of versioning resources, and I would even dare to say it makes sense mostly in the context of possible integration with Git-based workflows outside of CKAN in the future (e.g. people pushing / pulling data packages from a Git repo and this is also reflected in CKAN). Otherwise, a much simpler approach could be used to solve revisioned storage for resources. 

That said, I agree that there is a use case for many current CKAN users with a simple, easy to use cloud storage extension that handles everything - I think this one could evolve to be it, but in our current context of projects there was no justification to build it. I see no reason not to do it in the future, adding resource handling to the current code should really be easy and not complicate things as long as we do not collide with `ckanext-blob-storage` and the LFS flow (we probably won't because `ckanext-blob-storage` basically hijacks blueprints / templates and doesn't even touch the `IUploader` provided uploader).

**Comment by shevron** [comment]
@amercader Thanks for the input. I'm closing this for now, please reopen if you want to further discuss or create specific issues.

**Comment by rufuspollock** [comment]
@shevron 

> The LFS route makes sense only in the context of versioning resources, and I would even dare to say it makes sense mostly in the context of possible integration with Git-based workflows outside of CKAN in the future (e.g. people pushing / pulling data packages from a Git repo and this is also reflected in CKAN). Otherwise, a much simpler approach could be used to solve revisioned storage for resources.

This is not strictly correct. The LFS route makes sense if you are backing onto git or similar or want direct to cloud uploads (you then need something that hands out auth tokens etc). **giftless* is **not** about versioning so much as **direct to cloud** uploads ...

In summary this means that a giftless deployment should be very common (irrespective of whether you do versioning or not).

/cc @amercader

**Comment by amercader** [comment]
@shevron thanks for your comment, it makes a lot of sense

@rufuspollock can you expand on why LFS is necessary to allow direct to cloud uploads? This is what I'm really missing as I don't understand where git fits in a scenario [like this](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-UsingHTTPPOST.html)

**Comment by rufuspollock** [comment]
@amercader best intro is https://tech.datopian.com/blob-storage/#direct-to-cloud-upload - for direct to cloud you always need something that issues tokens that permit uploads i.e. a "Storage Access Token Service". You could write your own (and i/we have done) but after reflection we were like: that's pretty much what a git lfs server does in its essence and if we adopt that protocol we get some git compatibility for free which is what we did. Thinking about git here btw really can confuse you: the essence of git lfs **server** has *nothing* to do with git - it's a basically just something that hands out token to write to a content addressed storage system. Can explain more on a call if that is not clear yet.
